export { loadDesignSystem } from './design-system.js'
export type { DesignSystem } from './design-system.js'
export { extractCandidatesWithPositions, createScanner } from './scanner.js'
export type { CandidateWithPosition, SourceEntry } from './scanner.js'
export { findNonCanonicalClasses } from './canonicalize.js'
export type { Diagnostic, CanonicalizeOptions } from './canonicalize.js'
export { applyFixes } from './fixer.js'
export { findUnsortedClasses } from './sorter.js'
export type { SortStrategy, SortOptions } from './sorter.js'
export { formatDiagnostics } from './reporter.js'
export type { ReporterOptions } from './reporter.js'
